services:
  booklore:
    image: ghcr.io/booklore-app/booklore:latest
    container_name: booklore
    env_file:
      - .env.production
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/booklore
      - DATABASE_USERNAME=${DATABASE_USERNAME:-booklore}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED:-false}
      - FORCE_DISABLE_OIDC=${FORCE_DISABLE_OIDC:-false}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "${BOOKLORE_PORT:-6060}:6060"
    volumes:
      - ./data:/app/data
      - ./books:/books
      - ./bookdrop:/bookdrop
    healthcheck:
      test: wget -q -O - http://localhost:6060/api/v1/healthcheck
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.8
    container_name: mariadb
    env_file:
      - .env.production
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-booklore}
      - MYSQL_USER=${MYSQL_USER:-booklore}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./config:/config
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
